#!/bin/bash
clear
tput setaf 3; tput setab 6; tput bold; printf '%28s%s%-18s\n' "CRIAR USUÁRIO SSH"; tput sgr0; 
tput setaf 1; tput bold; read -p "Nome do Usuário: " usuario; tput sgr0; 
erro=$(getent passwd | cut -d \: -f1 | grep -w $usuario | wc -l) 

if [ "$erro" -ge "1" ]; then
	tput setaf 1; tput bold; echo "Usuário já existente"; tput sgr0; 
	exit 0

else
	tput setaf 1; tput bold; read -p "Senha: " senha; tput sgr0; 
	
	tput setaf 1; tput bold; read -p "Quantos dias irá durar? " dias; tput sgr0;
	if (echo $dias | egrep '[^0-9]' 1> /dev/null); then
	tput setaf 3; tput bold; echo  "Insira uma data correta!"; tput sgr0; 
else
	tput setaf 1; tput bold; read -p "Número de conexões simultâneas: " limite; tput sgr0;

	validade=$(date '+%C%y/%m/%d' -d " +$dias days")
	
	validadebrasil=$(date '+%d/%m/%C%y' -d " +$dias days")

	useradd -M -s /bin/false $usuario -e $validade
	
	usermod -p $(openssl passwd -1 $senha) $usuario

	tput setaf 2; tput bold; echo "Usuário $usuario criado com sucesso!"; tput sgr0; 
	tput setaf 2; tput bold; echo "Data de expiração $validadebrasil"; tput sgr0;
	tput setaf 3; tput setab 6; tput bold; printf '%28s%s%-18s\n' "-----------------------"; tput sgr0;
	echo "$usuario $limite" >> /root/usuarios.txt  
fi

fi