#!/bin/bash
clear
tput setaf 3; tput setab 6; tput bold; printf '%28s%s%-18s\n' "DELETAR USUÁRIO SSH"; tput sgr0; 
tput setaf 1; tput bold; read -p "Nome do Usuário: " usuario; tput sgr0; 

tput setaf 3; tput bold; read -p "Você tem certeza que deseja excluir o usuário $usuario? s/n: " resposta; tput sgr0; 

if [ "$resposta" == "s" ] || [ "$resposta" == "S" ] || [ -z "$resposta" ]; then
	cat /root/usuarios.txt | grep -v $usuario > /root/arquivo.new 
	mv /root/arquivo.new /root/usuarios.txt
	userdel --force $usuario &> /dev/null
	tput setaf 2; tput bold; echo "Usuário $usuario deletado com sucesso!"; tput sgr0; 
 
else
	tput setaf 2; tput bold; echo "Saindo..."; tput sgr0; 
	exit
fi

