#!/bin/bash
clear
lista="/root/usuarios.txt"
echo $$ > /tmp/kids
while true
do
tput setaf 3 ; tput setab 6 ; tput bold ; printf '%28s%s%-18s\n' "Monitor SSH"
tput setaf 3 ; tput setab 6 ; printf '  %-30s%s\n' "Usuário" "Conexão/Limite " ; echo "" ; tput sgr0
	while read usline
	do
		user="$(echo $usline | cut -d' ' -f1)"
		s2ssh="$(echo $usline | cut -d' ' -f2)"
		if [ -z "$user" ] ; then
			echo "" > /dev/null
		else
			ps x | grep [[:space:]]$user[[:space:]] | grep -v grep | grep -v pts > /tmp/tmp8
			s1ssh="$(cat /tmp/tmp8 | wc -l)"
			tput setaf 3 ; tput bold ; printf '  %-35s%s\n' $user $s1ssh/$s2ssh; tput sgr0
			tput setaf 3; tput setab 6; tput bold; printf '%28s%s%-18s\n' "------------------------"; tput sgr0;
		fi
	done < "$lista"
	echo ""
	exit 1
done